package pl.allegro.tech.allwrite.recipes.spring

import org.openrewrite.Recipe
import pl.allegro.tech.allwrite.recipes.gradle.ChangeGradleDependency

internal fun upgradeTestcontainersToV2(): List<Recipe> =
    TESTCONTAINERS_MODULES.map { artifactId ->
        ChangeGradleDependency(
            oldGroupId = "org.testcontainers",
            oldArtifactId = artifactId,
            newArtifactId = "testcontainers-$artifactId",
        )
    }

private val TESTCONTAINERS_MODULES = listOf(
    "activemq",
    "azure",
    "cassandra",
    "chromadb",
    "clickhouse",
    "cockroachdb",
    "consul",
    "couchbase",
    "cratedb",
    "database-commons",
    "databend",
    "db2",
    "elasticsearch",
    "gcloud",
    "grafana",
    "hivemq",
    "influxdb",
    "jdbc",
    "junit-jupiter",
    "k3s",
    "k6",
    "kafka",
    "ldap",
    "localstack",
    "mariadb",
    "milvus",
    "minio",
    "mockserver",
    "mongodb",
    "mssqlserver",
    "mysql",
    "neo4j",
    "nginx",
    "oceanbase",
    "ollama",
    "openfga",
    "oracle-free",
    "oracle-xe",
    "orientdb",
    "pinecone",
    "postgresql",
    "presto",
    "pulsar",
    "qdrant",
    "questdb",
    "r2dbc",
    "rabbitmq",
    "redpanda",
    "scylladb",
    "selenium",
    "solace",
    "solr",
    "spock",
    "tidb",
    "timeplus",
    "toxiproxy",
    "trino",
    "typesense",
    "vault",
    "weaviate",
    "yugabytedb",
)
