name: CI

on:
  pull_request:
  workflow_dispatch:
    inputs:
      build-cache:
        description: Build Cache
        type: choice
        default: enabled
        options:
          - enabled
          - disabled
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: false

      - run: ./gradlew check ${{ inputs.build-cache == 'disabled' && '--no-build-cache' || '' }}

      - uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: '**/test-results/*/*.xml'

      - uses: allegro-actions/dependabot-automerge@v1
